
Swisscom:
  SimpleSamlServiceProvider:
    authSource: default-sp
    authTokenCookieName: SimpleSAMLAuthToken
    attributeKeys:
      # ADFS claim: The unique name of the user
      username: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'
    loginParams: {  }
      #'ReturnTo': ''
Neos:
  Flow:
    security:
      authentication:
        providers:
          SamlProvider:
            token: Swisscom\SimpleSamlServiceProvider\Security\Authentication\Token\SamlToken
            provider: Swisscom\SimpleSamlServiceProvider\Security\Authentication\Provider\SamlProvider
            #entryPoint: 'Saml'
            #entryPointOptions:
            #  loginParams:
            #    'ReturnTo': ''
            #entryPoint: 'WebRedirect'
            #entryPointOptions:
            #  routeValues:
            #    '@package': 'Swisscom.SimpleSamlServiceProvider'
            #    '@controller': 'Authentication'
            #    '@action': 'index'
            #    '@format': 'html'
